### ISSUE TITLE
Log interferences with logback.xml inside jdbc jar

### ISSUE THREAD

**Issue by sebobr** [firebolt-db/jdbc#111]
Hi people,

I am developing on an app which include firebolt jdbc driver as a jar dependency (currently version 1.25). The app is built around Spring Boot framework with Maven.
We are trying to upgrade our jdbc driver to current version, and while working on this upgrade I ran into an issue with logback.xml file included inside the jar : our project does not include a logback.xml file itself, but Spring automatically search for a file with that name inside the classpath and loads firebolt file and override logging config with this config. So the whole app logs are written in the log files inside .firebolt directory.

A short term solution for us would be to include a log config in the form of a logback.xml config from our root app, but this is not suitable long term.

From what I have seen about this kind of issue in other github projects, I think it would be better to simply remove this file from the jar, in order to avoid collisions with other frameworks if projects want include firebolt dependency.

What do you think ?

**Comment by aymeric-dispa** [comment]
Hi @sebobr 
Thanks for the suggestion 👍. 
Yes I agree, it makes sense to remove it from our repo - I'll do that very soon (this will be part of our next release).
